#!/usr/bin/env bash
set -e

# 1) Crea las carpetas donde JupyterLab lee los settings
mkdir -p ~/.jupyter/lab/user-settings/@jupyterlab/apputils-extension
mkdir -p ~/.jupyter/lab/user-settings/@jupyterlab/completer-extension
mkdir -p ~/.jupyter/lab/user-settings/@jupyterlab/terminal-extension
mkdir -p ~/.jupyter/lab/user-settings/@jupyterlab/fileeditor-extension

# 2) Copia cada JSON desde tu repo al home de Jupyter
cp "$PWD/.jupyter/lab/user-settings/@jupyterlab/apputils-extension/themes.jupyterlab-settings" \
   ~/.jupyter/lab/user-settings/@jupyterlab/apputils-extension/
cp "$PWD/.jupyter/lab/user-settings/@jupyterlab/apputils-extension/notifications.jupyterlab-settings" \
   ~/.jupyter/lab/user-settings/@jupyterlab/apputils-extension/
cp "$PWD/.jupyter/lab/user-settings/@jupyterlab/completer-extension/plugin.jupyterlab-settings" \
   ~/.jupyter/lab/user-settings/@jupyterlab/completer-extension/
cp "$PWD/.jupyter/lab/user-settings/@jupyterlab/terminal-extension/plugin.jupyterlab-settings" \
   ~/.jupyter/lab/user-settings/@jupyterlab/terminal-extension/
cp "$PWD/.jupyter/lab/user-settings/@jupyterlab/fileeditor-extension/plugin.jupyterlab-settings" \
   ~/.jupyter/lab/user-settings/@jupyterlab/fileeditor-extension/
